[package]
name = "api"
version = "0.0.1"
authors = ["Jan KÃ¼hle <jan.kuehle@codecentric.de>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde_json = "1.0.61"
wascc-actor = "0.7.4"

[profile.release]
# Optimize for small code size
opt-level = "s"
lto = true
